

export const weatherData = {
  location: {
    name: "London",
    region: "City of London, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.11,
    tz_id: "Europe/London",
    localtime_epoch: 1698696499,
    localtime: "2023-10-30 20:08",
  },
  current: {
    last_updated_epoch: 1698696000,
    last_updated: "2023-10-30 20:00",
    temp_c: 10.0,
    temp_f: 50.0,
    is_day: 0,
    condition: {
      text: "Mist",
      icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
      code: 1030,
    },
    wind_mph: 3.8,
    wind_kph: 6.1,
    wind_degree: 220,
    wind_dir: "SW",
    pressure_mb: 996.0,
    pressure_in: 29.41,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 87,
    cloud: 0,
    feelslike_c: 9.4,
    feelslike_f: 49.0,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 6.6,
    gust_kph: 10.7,
  },
  forecast: {
    forecastday: [
      {
        date: "2023-10-30",
        date_epoch: 1698624000,
        day: {
          maxtemp_c: 14.4,
          maxtemp_f: 58.0,
          mintemp_c: 9.9,
          mintemp_f: 49.9,
          avgtemp_c: 11.7,
          avgtemp_f: 53.1,
          maxwind_mph: 11.2,
          maxwind_kph: 18.0,
          totalprecip_mm: 1.95,
          totalprecip_in: 0.08,
          totalsnow_cm: 0.0,
          avgvis_km: 9.9,
          avgvis_miles: 6.0,
          avghumidity: 82.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 78,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 3.0,
        },
        astro: {
          sunrise: "06:50 AM",
          sunset: "04:37 PM",
          moonrise: "05:08 PM",
          moonset: "09:02 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 98,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1698624000,
            time: "2023-10-30 00:00",
            temp_c: 11.1,
            temp_f: 52.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 208,
            wind_dir: "SSW",
            pressure_mb: 994.0,
            pressure_in: 29.35,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 81,
            cloud: 29,
            feelslike_c: 8.9,
            feelslike_f: 48.1,
            windchill_c: 8.9,
            windchill_f: 48.1,
            heatindex_c: 11.1,
            heatindex_f: 52.0,
            dewpoint_c: 8.0,
            dewpoint_f: 46.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.5,
            gust_kph: 29.8,
            uv: 1.0,
          },
          {
            time_epoch: 1698627600,
            time: "2023-10-30 01:00",
            temp_c: 11.0,
            temp_f: 51.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 206,
            wind_dir: "SSW",
            pressure_mb: 994.0,
            pressure_in: 29.35,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 82,
            cloud: 32,
            feelslike_c: 8.9,
            feelslike_f: 48.1,
            windchill_c: 8.9,
            windchill_f: 48.1,
            heatindex_c: 11.0,
            heatindex_f: 51.7,
            dewpoint_c: 8.1,
            dewpoint_f: 46.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.1,
            gust_kph: 27.5,
            uv: 1.0,
          },
          {
            time_epoch: 1698631200,
            time: "2023-10-30 02:00",
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 204,
            wind_dir: "SSW",
            pressure_mb: 994.0,
            pressure_in: 29.35,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 83,
            cloud: 31,
            feelslike_c: 8.9,
            feelslike_f: 48.1,
            windchill_c: 8.9,
            windchill_f: 48.1,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 8.2,
            dewpoint_f: 46.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.4,
            gust_kph: 26.4,
            uv: 1.0,
          },
          {
            time_epoch: 1698634800,
            time: "2023-10-30 03:00",
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 199,
            wind_dir: "SSW",
            pressure_mb: 994.0,
            pressure_in: 29.35,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 26,
            feelslike_c: 9.0,
            feelslike_f: 48.1,
            windchill_c: 9.0,
            windchill_f: 48.1,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 8.4,
            dewpoint_f: 47.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.2,
            gust_kph: 26.0,
            uv: 1.0,
          },
          {
            time_epoch: 1698638400,
            time: "2023-10-30 04:00",
            temp_c: 10.8,
            temp_f: 51.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 994.0,
            pressure_in: 29.36,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 10,
            feelslike_c: 9.0,
            feelslike_f: 48.2,
            windchill_c: 9.0,
            windchill_f: 48.2,
            heatindex_c: 10.8,
            heatindex_f: 51.5,
            dewpoint_c: 8.3,
            dewpoint_f: 47.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.2,
            gust_kph: 24.4,
            uv: 1.0,
          },
          {
            time_epoch: 1698642000,
            time: "2023-10-30 05:00",
            temp_c: 10.7,
            temp_f: 51.2,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 197,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.38,
            precip_mm: 0.03,
            precip_in: 0.0,
            humidity: 85,
            cloud: 76,
            feelslike_c: 8.9,
            feelslike_f: 48.0,
            windchill_c: 8.9,
            windchill_f: 48.0,
            heatindex_c: 10.7,
            heatindex_f: 51.2,
            dewpoint_c: 8.2,
            dewpoint_f: 46.8,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.9,
            gust_kph: 23.9,
            uv: 1.0,
          },
          {
            time_epoch: 1698645600,
            time: "2023-10-30 06:00",
            temp_c: 10.5,
            temp_f: 50.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 203,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.37,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 9,
            feelslike_c: 9.0,
            feelslike_f: 48.1,
            windchill_c: 9.0,
            windchill_f: 48.1,
            heatindex_c: 10.5,
            heatindex_f: 50.9,
            dewpoint_c: 8.3,
            dewpoint_f: 47.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.9,
            gust_kph: 20.8,
            uv: 1.0,
          },
          {
            time_epoch: 1698649200,
            time: "2023-10-30 07:00",
            temp_c: 10.3,
            temp_f: 50.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 196,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.38,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 22,
            feelslike_c: 9.0,
            feelslike_f: 48.2,
            windchill_c: 9.0,
            windchill_f: 48.2,
            heatindex_c: 10.3,
            heatindex_f: 50.5,
            dewpoint_c: 8.4,
            dewpoint_f: 47.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.2,
            uv: 4.0,
          },
          {
            time_epoch: 1698652800,
            time: "2023-10-30 08:00",
            temp_c: 10.7,
            temp_f: 51.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 183,
            wind_dir: "S",
            pressure_mb: 996.0,
            pressure_in: 29.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 30,
            feelslike_c: 9.6,
            feelslike_f: 49.3,
            windchill_c: 9.6,
            windchill_f: 49.3,
            heatindex_c: 10.7,
            heatindex_f: 51.2,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 4.0,
          },
          {
            time_epoch: 1698656400,
            time: "2023-10-30 09:00",
            temp_c: 11.7,
            temp_f: 53.1,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 177,
            wind_dir: "S",
            pressure_mb: 995.0,
            pressure_in: 29.4,
            precip_mm: 0.01,
            precip_in: 0.0,
            humidity: 85,
            cloud: 56,
            feelslike_c: 10.7,
            feelslike_f: 51.2,
            windchill_c: 10.7,
            windchill_f: 51.2,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            dewpoint_c: 9.3,
            dewpoint_f: 48.7,
            will_it_rain: 1,
            chance_of_rain: 78,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 3.0,
          },
          {
            time_epoch: 1698660000,
            time: "2023-10-30 10:00",
            temp_c: 12.9,
            temp_f: 55.2,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 190,
            wind_dir: "S",
            pressure_mb: 996.0,
            pressure_in: 29.4,
            precip_mm: 0.44,
            precip_in: 0.02,
            humidity: 80,
            cloud: 82,
            feelslike_c: 11.8,
            feelslike_f: 53.3,
            windchill_c: 11.8,
            windchill_f: 53.3,
            heatindex_c: 12.9,
            heatindex_f: 55.2,
            dewpoint_c: 9.6,
            dewpoint_f: 49.3,
            will_it_rain: 0,
            chance_of_rain: 58,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 10.6,
            gust_kph: 17.0,
            uv: 3.0,
          },
          {
            time_epoch: 1698663600,
            time: "2023-10-30 11:00",
            temp_c: 13.5,
            temp_f: 56.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 199,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 77,
            cloud: 41,
            feelslike_c: 12.6,
            feelslike_f: 54.6,
            windchill_c: 12.6,
            windchill_f: 54.6,
            heatindex_c: 13.5,
            heatindex_f: 56.3,
            dewpoint_c: 9.5,
            dewpoint_f: 49.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.0,
            gust_kph: 16.1,
            uv: 4.0,
          },
          {
            time_epoch: 1698667200,
            time: "2023-10-30 12:00",
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 203,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.4,
            precip_mm: 0.37,
            precip_in: 0.01,
            humidity: 72,
            cloud: 84,
            feelslike_c: 13.1,
            feelslike_f: 55.6,
            windchill_c: 13.1,
            windchill_f: 55.6,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 9.2,
            dewpoint_f: 48.6,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.2,
            uv: 3.0,
          },
          {
            time_epoch: 1698670800,
            time: "2023-10-30 13:00",
            temp_c: 14.4,
            temp_f: 57.9,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 212,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.38,
            precip_mm: 0.01,
            precip_in: 0.0,
            humidity: 69,
            cloud: 75,
            feelslike_c: 13.7,
            feelslike_f: 56.7,
            windchill_c: 13.7,
            windchill_f: 56.7,
            heatindex_c: 14.4,
            heatindex_f: 57.9,
            dewpoint_c: 8.9,
            dewpoint_f: 48.0,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.1,
            gust_kph: 14.6,
            uv: 3.0,
          },
          {
            time_epoch: 1698674400,
            time: "2023-10-30 14:00",
            temp_c: 14.4,
            temp_f: 58.0,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 995.0,
            pressure_in: 29.37,
            precip_mm: 0.04,
            precip_in: 0.0,
            humidity: 68,
            cloud: 74,
            feelslike_c: 14.0,
            feelslike_f: 57.2,
            windchill_c: 14.0,
            windchill_f: 57.2,
            heatindex_c: 14.5,
            heatindex_f: 58.0,
            dewpoint_c: 8.7,
            dewpoint_f: 47.6,
            will_it_rain: 0,
            chance_of_rain: 63,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 3.0,
          },
          {
            time_epoch: 1698678000,
            time: "2023-10-30 15:00",
            temp_c: 14.0,
            temp_f: 57.2,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 209,
            wind_dir: "SSW",
            pressure_mb: 994.0,
            pressure_in: 29.36,
            precip_mm: 0.33,
            precip_in: 0.01,
            humidity: 71,
            cloud: 72,
            feelslike_c: 14.0,
            feelslike_f: 57.3,
            windchill_c: 14.0,
            windchill_f: 57.3,
            heatindex_c: 14.0,
            heatindex_f: 57.2,
            dewpoint_c: 8.9,
            dewpoint_f: 48.1,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 5.2,
            gust_kph: 8.4,
            uv: 3.0,
          },
          {
            time_epoch: 1698681600,
            time: "2023-10-30 16:00",
            temp_c: 12.9,
            temp_f: 55.2,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 211,
            wind_dir: "SSW",
            pressure_mb: 994.0,
            pressure_in: 29.36,
            precip_mm: 0.65,
            precip_in: 0.03,
            humidity: 79,
            cloud: 89,
            feelslike_c: 12.7,
            feelslike_f: 54.8,
            windchill_c: 12.7,
            windchill_f: 54.8,
            heatindex_c: 12.9,
            heatindex_f: 55.1,
            dewpoint_c: 9.4,
            dewpoint_f: 48.9,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 6.4,
            gust_kph: 10.2,
            uv: 3.0,
          },
          {
            time_epoch: 1698685200,
            time: "2023-10-30 17:00",
            temp_c: 12.1,
            temp_f: 53.8,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 219,
            wind_dir: "SW",
            pressure_mb: 995.0,
            pressure_in: 29.38,
            precip_mm: 0.07,
            precip_in: 0.0,
            humidity: 83,
            cloud: 74,
            feelslike_c: 12.1,
            feelslike_f: 53.7,
            windchill_c: 12.1,
            windchill_f: 53.7,
            heatindex_c: 12.1,
            heatindex_f: 53.8,
            dewpoint_c: 9.3,
            dewpoint_f: 48.8,
            will_it_rain: 0,
            chance_of_rain: 61,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.7,
            gust_kph: 9.2,
            uv: 1.0,
          },
          {
            time_epoch: 1698688800,
            time: "2023-10-30 18:00",
            temp_c: 11.9,
            temp_f: 53.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 237,
            wind_dir: "WSW",
            pressure_mb: 995.0,
            pressure_in: 29.38,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 15,
            feelslike_c: 11.9,
            feelslike_f: 53.3,
            windchill_c: 11.9,
            windchill_f: 53.3,
            heatindex_c: 11.9,
            heatindex_f: 53.5,
            dewpoint_c: 9.3,
            dewpoint_f: 48.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.7,
            gust_kph: 9.2,
            uv: 1.0,
          },
          {
            time_epoch: 1698692400,
            time: "2023-10-30 19:00",
            temp_c: 11.5,
            temp_f: 52.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 996.0,
            pressure_in: 29.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 15,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 11.5,
            heatindex_f: 52.7,
            dewpoint_c: 9.3,
            dewpoint_f: 48.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.2,
            gust_kph: 10.0,
            uv: 1.0,
          },
          {
            time_epoch: 1698696000,
            time: "2023-10-30 20:00",
            temp_c: 10.0,
            temp_f: 50.0,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 220,
            wind_dir: "SW",
            pressure_mb: 996.0,
            pressure_in: 29.41,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 0,
            feelslike_c: 10.6,
            feelslike_f: 51.0,
            windchill_c: 10.6,
            windchill_f: 51.0,
            heatindex_c: 11.0,
            heatindex_f: 51.7,
            dewpoint_c: 9.1,
            dewpoint_f: 48.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.6,
            gust_kph: 10.7,
            uv: 1.0,
          },
          {
            time_epoch: 1698699600,
            time: "2023-10-30 21:00",
            temp_c: 10.5,
            temp_f: 51.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 245,
            wind_dir: "WSW",
            pressure_mb: 997.0,
            pressure_in: 29.43,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 10,
            feelslike_c: 10.1,
            feelslike_f: 50.1,
            windchill_c: 10.1,
            windchill_f: 50.1,
            heatindex_c: 10.5,
            heatindex_f: 51.0,
            dewpoint_c: 8.9,
            dewpoint_f: 48.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.6,
            gust_kph: 10.6,
            uv: 1.0,
          },
          {
            time_epoch: 1698703200,
            time: "2023-10-30 22:00",
            temp_c: 10.2,
            temp_f: 50.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 237,
            wind_dir: "WSW",
            pressure_mb: 997.0,
            pressure_in: 29.44,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 90,
            cloud: 9,
            feelslike_c: 9.8,
            feelslike_f: 49.6,
            windchill_c: 9.8,
            windchill_f: 49.6,
            heatindex_c: 10.2,
            heatindex_f: 50.4,
            dewpoint_c: 8.7,
            dewpoint_f: 47.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 1.0,
          },
          {
            time_epoch: 1698706800,
            time: "2023-10-30 23:00",
            temp_c: 9.9,
            temp_f: 49.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 997.0,
            pressure_in: 29.45,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 91,
            cloud: 10,
            feelslike_c: 9.5,
            feelslike_f: 49.0,
            windchill_c: 9.5,
            windchill_f: 49.0,
            heatindex_c: 9.9,
            heatindex_f: 49.9,
            dewpoint_c: 8.5,
            dewpoint_f: 47.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};
